### ISSUE TITLE
Error when clicking sign out from a document edit view

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#454]
### Steps to reproduce the problem

1. Sign in
2. Navigate to a collection and select a section (e.g. http://publish-develop.eb.dev.dadi.technology/articles/39c7113b-69be-4121-b815-a423b766844a/details)
3. Click sign out
4. Observe that the user is not redirected to the sign in page, even though the session was indeed destroyed

**Comment by eduardoboucas** [comment]
I believe this has been fixed. Can anyone replicate?

**Comment by davidmacp** [comment]
@eduardoboucas 

I am still seeing this in http://publish-develop.eb.dev.dadi.technology/

Even trying to sign out from http://publish-develop.eb.dev.dadi.technology/articles gets the following:

![screen shot 2018-08-29 at 1 29 48 pm](https://user-images.githubusercontent.com/36462430/44763774-060dad00-ab90-11e8-8922-2617797db815.png)

**Comment by eduardoboucas** [comment]
@davidmacp it was indeed part of #469. Those changes have been merged into `develop` now, so can you please re-test and close the issue if the problem is gone?

Thanks!

**Comment by davidmacp** [comment]
Working as expected now. Ok to close.
